/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:f644f8e2-c7df-433c-b07c-bab0e2d1a859",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_OuIoaTDqz",
    "aws_user_pools_web_client_id": "9hmsfn3o4663am3fbhmc7q7dt",
    "oauth": {}
};


export default awsmobile;
